/* THIS MUST BE THE FIRST LINE AS IT NEEDS TO BE ID 1 IN DATABASE ! */
INSERT INTO "CATEGORIES" (NAME) VALUES ('undefined');

/* Set the default config */
INSERT INTO "APP_CONFIG" (CONFIG_NAME, CONFIG_VALUE) VALUES ('shippingFees', '9.99');